name: wiki

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Ready to build
      run: |
        yarn
        rm -rf docs/*
        cp -r ../* docs/
        node create.index.js
        cat index.md >> docs/README.md
        yarn run docs:build
      working-directory: ./.wiki
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: pravusid/wiki
        publish_branch: gh-pages
        publish_dir: ./.wiki/docs/.vuepress/dist
